# Generated by Django 2.2.4 on 2022-10-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('notional_id', models.IntegerField(null=True)),
                ('city', models.CharField(max_length=30)),
                ('blood_type', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('city', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('police_to_driver', models.ManyToManyField(related_name='drivertopolice', to='first_app.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Violaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
                ('fees', models.IntegerField(max_length=10)),
                ('resson', models.CharField(max_length=255)),
                ('violation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dviolations', to='first_app.Driver')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pviolations', to='first_app.Police')),
            ],
        ),
        migrations.CreateModel(
            name='Vechile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_model', models.CharField(max_length=30)),
                ('vechile_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vechiles', to='first_app.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relased_date', models.DateField()),
                ('expierd_date', models.DateField()),
                ('vechile_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.Driver')),
            ],
        ),
    ]
