# Generated by Django 2.2.4 on 2022-10-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_violaion_expierd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='police',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='violaion',
            name='fees',
            field=models.IntegerField(),
        ),
    ]
