# Generated by Django 2.2.4 on 2022-10-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20221010_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violaion',
            name='vechile_model',
        ),
        migrations.RemoveField(
            model_name='violaion',
            name='vechile_number',
        ),
        migrations.RemoveField(
            model_name='violaion',
            name='violation_date',
        ),
    ]
