# Generated by Django 2.2.4 on 2022-10-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20221010_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violaion',
            old_name='expierd_date',
            new_name='violation_date',
        ),
    ]
