# Generated by Django 2.2.4 on 2022-10-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20221010_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Violaion',
            new_name='Violation',
        ),
    ]
