# Generated by Django 4.1.1 on 2022-10-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20221010_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='resson',
            field=models.CharField(max_length=120),
        ),
    ]
