# Generated by Django 2.2.4 on 2022-10-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='status',
            field=models.CharField(default='Not paid', max_length=20),
        ),
    ]
