# Generated by Django 2.2.4 on 2022-10-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_violation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='status',
            field=models.CharField(default='Not paid', max_length=20, null=True),
        ),
    ]
