# Generated by Django 2.2.4 on 2022-10-13 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_auto_20221012_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivermessage', to='first_app.Driver')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policemessage', to='first_app.Police')),
            ],
        ),
    ]
